version: "3"

services:
  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - dependency-app

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    volumes:
    -  mongodb-data:/bitnami/mongodb
  
  dependency-app:
    image: ubuntu
    command: tail -F anything

volumes:
  mongodb-data: